### ISSUE TITLE
Webpack Compilation Error on Cypress 13

### ISSUE THREAD

**Issue by h2oearth** [bahmutov/cypress-each#114]
I am in the process of upgrading from Cypress 12 to 13, but the specs that use `cypress-each` are failing at load time. I am using the latest `cypress-each`. I do not know what else to try to make this work :-(

```
Error: Webpack Compilation Error
Module not found: Error: Can't resolve 'process/browser.js' in '/Users/superman/wrk/my-repos/node_modules/util'

Cannot read properties of undefined (reading 'module')
    at Watching.handle [as handler] (/Users/superman/Library/Caches/Cypress/13.6.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:212:23)
    at /Users/superman/Library/Caches/Cypress/13.6.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:303:9
    at Hook.eval [as callAsync] (eval at create (/Users/superman/Library/Caches/Cypress/13.6.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Watching._done (/Users/superman/Library/Caches/Cypress/13.6.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:299:28)
    at /Users/superman/Library/Caches/Cypress/13.6.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:213:21
    at Compiler.emitRecords (/Users/superman/Library/Caches/Cypress/13.6.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:919:5)
```

**Comment by h2oearth** [comment]
anyone with similar issue or updates?
